### ISSUE TITLE
server模式使用externals: webpack-node-externals

### ISSUE THREAD

**Issue by feix760** [hubcarl/easywebpack#10]
https://github.com/hubcarl/easywebpack/blob/c79e675276a98ffb7f593cd5f57433f7dec3b729/lib/server.js#L29

可以使用[webpack-node-externals](https://www.npmjs.com/package/webpack-node-externals)，省的生成一个很长很长的node_modules模块list

**Comment by hubcarl** [comment]
这个之前看过这个，没来急换

**Comment by hubcarl** [comment]
3.5.0-rc.7 版本已经用 webpack-node-externals 替换
