### ISSUE TITLE
该怎么样执行单元测试，在package.json里没有发现egg-bin命令的身影

### ISSUE THREAD

**Issue by gzlock** [hubcarl/easywebpack#12]
按照以下方法
https://github.com/eggjs/egg-sequelize/tree/master/test/fixtures/apps/model-app
想测试egg-sequelize model的配置
但是发现easywebpack生成的package.json没有包含egg-bin的命令

求解惑

**Comment by hubcarl** [comment]
easywebpack 与 egg 没关系, 你如果想用 egg-bin命令，自己安装添加即可

**Comment by hubcarl** [comment]
egg 的单元测试你可以用 egg-init 初始化一个插件和项目，内置了单元测试例子，可以 npm test 直接跑
