### ISSUE TITLE
在设置了 config.prefix 后，怎么让 html 编译在根目录呢

### ISSUE THREAD

**Issue by mice33** [hubcarl/easywebpack#15]
类似我想编译成这样

/xxx.html
/aaa.html
/static/js/xx.js
/static/css/css.js

感觉自己脑洞不够大。。在不改程序，现有逻辑下自己绕不过去

**Comment by mice33** [comment]
`
          static/js/common.2433930c.js    5.22 kB       0  [emitted]  common
       static/js/home/home.1d552e28.js  302 bytes       2  [emitted]  home/home
     static/js/about/about.5cb040c3.js  161 bytes       3  [emitted]  about/about
         static/js/runtime.7d063e42.js  799 bytes       4  [emitted]  runtime
   static/css/about/about.1f232752.css   13 bytes       3  [emitted]  about/about
     static/css/home/home.970d7f6a.css   26 bytes       2  [emitted]  home/home
static/css/nunjucks/index.edd03786.css   16 bytes       1  [emitted]  nunjucks/index
  static/js/nunjucks/index.98a9981b.js  186 bytes       1  [emitted]  nunjucks/index
               static/about/about.html  579 bytes          [emitted]
                 static/home/home.html  608 bytes          [emitted]
            static/nunjucks/index.html  925 bytes          [emitted]
`

设置 config.prefix 后，编译的 html 也在 static 目录里了

**Comment by hubcarl** [comment]
@mice33  你的用的是 easywebpack 4  版本 还是 easywebpack 3 版本？看结果好像是 3

**Comment by mice33** [comment]
@hubcarl 我使用的 3，easywebpack-cli 也提交了一个代码修复，你去看看

**Comment by hubcarl** [comment]
好的

**Comment by mice33** [comment]
@hubcarl 额，用 3 除非我自己改代码逻辑吧，4 可以用于生产了吗

**Comment by hubcarl** [comment]
@mice33  4可以用生产， 3的话我刚临时hack支持了一下, 设置 buildDir 为空，只是不规范，你可以用 3 这样配置：

```js
// webpack.config.js
module.exports = {
 prefix: 'static',
 entry: {
   buildDir: ''
 }
}

```

然后更新一下 easywebpack 3的依赖， 具体见：https://github.com/hubcarl/easywebpack/commit/2fed25b

**Comment by mice33** [comment]
唔 那你需要把 easywebpack-html 里的依赖更新一下，版本还是 "easywebpack": "^3.5.0"，我删除 package-lock.json 重新安装几次了，package-lock.json 里只能安装到 "easywebpack": "version": "3.7.1",

**Comment by hubcarl** [comment]
@mice33  npm cache clean --force  然后重新安装一下试试， 如果慢，可以 npm install --registry https://registry.npm.taobao.org

**Comment by mice33** [comment]
@hubcarl 我已经迁移成项目里自己调用 easywebpack 了，然后 easywebpack-cli 又提交了一个修复
