### ISSUE TITLE
建议: entry include 配置使用glob表达式

### ISSUE THREAD

**Issue by feix760** [hubcarl/easywebpack#33]
https://github.com/hubcarl/easywebpack/blob/a88803786f514269b5872ae5101d6a19e7ad4867/utils/utils.js#L90

直接用 `include: [ 'page/*/index.vue' ]` `glob`表达式配置include会不会清晰灵活一点

**Comment by hubcarl** [comment]
这个计划在 webpack5 里面改造一下

**Comment by hubcarl** [comment]
https://www.yuque.com/easy-team/easywebpack/entry

**Comment by hubcarl** [comment]
![image](https://user-images.githubusercontent.com/4983042/46666890-8f39ea00-cbfa-11e8-8b42-b3d74c874f48.png)
