### ISSUE TITLE
1.0.5 在 windows 下 crash

### ISSUE THREAD

**Issue by jacksky007** [hubcarl/easywebpack#6]
https://github.com/hubcarl/easywebpack/blob/master/utils/utils.js#L88

在我电脑上，这里 path.posix.join 返回结果为
temp/cache.json

对应 path.win32.join 返回结果为
D:\codes\egg-vue-webpack-boilerplate\node_modules\easywebpack-vue\node_modules\easywebpack\temp\cache.json

上面那个会导致找不到 module

就像我之前提的 pr 一样，一开始也是把 path 换成 path.posix，马上发现没这么简单。
win32 下我遇到的主要问题在于 entry 的路径，参见 https://github.com/jacksky007/easywebpack/blob/master/utils/utils.js#L53

**Comment by hubcarl** [comment]
@jacksky007  刚才测试的时候发现了，我已经修复了
