### ISSUE TITLE
为什么 webpack.config.js 中的 packs 选项是必须的?

### ISSUE THREAD

**Issue by feichao** [hubcarl/easywebpack#9]
如题.

**Comment by hubcarl** [comment]
packs 非必需，可以支持单独打包成js的功能。

**Comment by feichao** [comment]
我的错... 但是现在还不知道什么问题. 上次打包的时候没有加 packs 选项, webpack 打包总是报 entry 相关的错误, 加上了 packs 选项就正常了. 刚刚去掉试了下又 OK 了. 我这边再确认一下问题.

**Comment by hubcarl** [comment]
建议 easy print 命令检查 生成的 Webpack 配置
